x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - USER

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY}
    - LIBGL_ALWAYS_SOFTWARE=1
    - USER

services:
  rosbot_xl:
    image: rosbot-xl-dev 
    <<: [*gpu-config]
    network_mode: host
    ipc: host
    user: root
    entrypoint: /bin/bash     # 👈 disables the sim-launching ENTRYPOINT
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/ros2_ws/src:rw
      - /ros2_ws:/ros2_ws_mirror:rw
      - /opt/ros/humble:/opt/ros/humble_mirror:rw
      - ./scripts:/ros2_ws/scripts:rw

